version: '2'
volumes:
  ipython:
services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/code
      - /sounds/
      - /static/
      - ipython:/root/.ipython
    command: dumb-init python manage.py runserver 0.0.0.0:8000

